# Generated by Django 3.2.5 on 2021-08-01 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.CharField(blank=True, max_length=20)),
                ('flight_no', models.CharField(blank=True, max_length=20)),
                ('doj', models.DateField()),
                ('dst', models.CharField(max_length=100)),
                ('ast', models.CharField(max_length=100)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('doj', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('vseats', models.PositiveIntegerField()),
                ('passengers', models.ManyToManyField(blank=True, related_name='passenger_account_set', to=settings.AUTH_USER_MODEL)),
                ('qraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
